Add TB enrollment and followup forms
METS-Programme/openmrs-distro-referenceapplication pull request #5
Opened 2023-08-28 09:30 UTC by d-rita

Add TB enrollment and followup forms for DS and DR patients

2023-08-28 09:51 UTC, ODORA0 requested changes

2023-08-28 09:51 UTC, ODORA0 commented on dr-tb-enrollment-form.json
> +  "name": "DR TB: HMIS TB 001 Second Line TB Treatment Card - Enrollment Page",
Change name to `DR TB Enrollment Form`

2023-08-28 09:51 UTC, ODORA0 commented on dr-tb-followup.json
> +  "name": "DR TB: HMIS TB 001 Second Line TB Treatment Card - Followup Section",
Change name to `DR TB Followup Form`

2023-08-28 09:51 UTC, ODORA0 commented on ds-tb-enrollment.json
> +  "name": "DS TB: HMIS TB 003 TB Client Card - Enrollment Page",
Change name to `DS TB Enrollment Form`

2023-08-28 09:51 UTC, ODORA0 commented on ds-tb-followup.json
> +  "name": "DS TB: HMIS TB 003 TB Client Card - Followup Section",
Change name to `DS TB Followup Form`

2023-08-29 10:31 UTC, d-rita commented
Updated file names and moved files to ampath forms directory cc: @ODORA0

2023-08-29 11:55 UTC, merged